# Appleseed Core Stack Windows Composure
version: '2.1'
services:
  db-mssql-express-2016:
    build:
     context: c:\Appleseed\portal-stack\docker\db\mssql\
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: Y
    #Port 1433 is usually blocked externally on windows host.  If it is not, use a dynamic / blocked internal port
    ports:
      - "1433:1433"

  web-appleseed-portal:
    build:
      context: c:\Appleseed\portal-stack\docker\portal\windows\
    
    depends_on:
      - "db-mssql-express-2016"

    links:
      - "db-mssql-express-2016"
    #Port 80 is exposed on the container and host.  Admins can modify this in their own version. 
    ports:
      - "80:80"
 
  appleseed-base-engine:
   build:
     context : c:\Appleseed\search-stack\docker\engine\windows\
     
  search-index-solr:
   build :
     context : c:\Appleseed\search-stack\docker\solr\windows\nanoserver
   #To-do : Expose port 81 for IIS AAR Passthrough security.  However if 8983 is blocked form outside should be good
   ports:
      - "8983:8983"
     
  search-index-elastic:
   build :
     context : c:\Appleseed\search-stack\docker\elastic\windows\nanoserver
    

networks:
    default:
       external:
           name: nat
