# Appleseed Core Stack Azure Business Composure
# Light composure with an integrated solr and engine container.  Good for small business
version: '2.1'
services:

  web-appleseed-portal:
    build:
      context: c:\Appleseed\portal-stack\docker\portal\windows\
   
    #Port 80 is exposed on the container and host.  Admins can modify this in their own version. 
    ports:
      - "80:80"
   
  search-index-solr-base:
   build :
     context : c:\Appleseed\search-stack\docker\solr\windows\int.engine\
    #using the solr integrated with engine container
   ports:
      - "8983:8983"
     
  db-nosql-cassandra:
    build :
     context : c:\Appleseed\search-stack\docker\cassandra\windows\
    #Grap Random internal port for now for security
    #ports:
    # - "7000" 
    

networks:
    default:
       external:
           name: nat
