# Appleseed Core Stack Azure Enterprise Composure
# To-Do : Add traefik
version: '2.1'
services:

  web-appleseed-portal:
    build:
      context: c:\Appleseed\portal-stack\docker\portal\windows\
   
    #Port 80 is exposed on the container and host.  Admins can modify this in their own version. 
    ports:
      - "80:80"
 
  engine-appleseed-base:
    build:
     context : c:\Appleseed\search-stack\docker\engine\windows\
     
  db-nosql-cassandra:
    build :
     context : c:\Appleseed\search-stack\docker\cassandra\windows\
    
    ports:
     - "7000:7000" 
     
  search-index-solr:
    build :
     context : c:\Appleseed\search-stack\docker\solr\windows\nanoserver\latest
    
    ports:
       - "8983:8983"
        
networks:
    default:
       external:
           name: nat
